import {
  MetricData,
  VerificationSession,
  AttentionItem,
  InstrumentPreset,
  ComplianceData,
  DemoScenario,
} from './types';

export const INITIAL_METRICS: MetricData = {
  activeVerifications: 12,
  pendingSignOff: 3,
  passRate24h: 94.2,
  traceability: 100,
};

export const CURRENT_HERO_SESSION = {
  id: 'VR-2026-00418',
  sessionNumber: 'VR-2026-00418',
  instrument: 'Avery Class III Retail',
  model: 'Retail Platform 30',
  manufacturer: 'Avery Weigh-Tronix',
  class: 'Class III',
  maxCapacity: '30 kg',
  interval: 'e = 0.005 kg',
  currentProcedure: 'Eccentricity / Corner Loading',
  completedSteps: 4,
  totalSteps: 7,
  progressPercent: 57,
  steps: [
    { num: 1, label: 'Visual Inspection', status: 'PASS' as const },
    { num: 2, label: 'Zero & Tare Setting', status: 'PASS' as const },
    { num: 3, label: 'Pre-Loading Cycle', status: 'PASS' as const },
    { num: 4, label: 'Eccentricity (Corner)', status: 'IN_PROGRESS' as const },
    { num: 5, label: 'Weighing Linearity', status: 'PENDING' as const },
    { num: 6, label: 'Repeatability Test', status: 'PENDING' as const },
    { num: 7, label: 'Supervisory Review', status: 'PENDING' as const },
  ],
};

export const INITIAL_ATTENTION_ITEMS: AttentionItem[] = [
  {
    id: 'att-1',
    severity: 'warning',
    title: 'Standard weight SW-042',
    description: 'Calibration certificate expires in 3 days',
    actionText: 'Review standard',
  },
  {
    id: 'att-2',
    severity: 'fail',
    title: 'VR-2026-00412',
    description: 'Eccentricity result requires review',
    actionText: 'Open session',
    sessionId: 'VR-2026-00412',
  },
];

export const INITIAL_VERIFICATION_SESSIONS: any[] = [
  {
    id: 'VR-2026-0142',
    sessionNumber: 'AV-2026-8812',
    instrument: 'Avery ZM201 Retail Platform',
    model: 'ZM201 Platform',
    manufacturer: 'Avery Weigh-Tronix',
    accuracyClass: 'Class III',
    maxCapacity: '30.000 kg',
    interval: 'e = 0.005 kg',
    procedure: 'Weighing Error',
    progressText: '3 / 7',
    status: 'PASS',
    updated: '4 min ago',
    actionText: 'Continue',
  },
  {
    id: 'VR-2026-0104',
    sessionNumber: 'MT-2026-1042',
    instrument: 'Mettler XP205 Laboratory',
    model: 'XP205 Micro Balance',
    manufacturer: 'Mettler Toledo',
    accuracyClass: 'Class I',
    maxCapacity: '120 g',
    interval: 'e = 1 mg',
    procedure: 'Review & Sign',
    progressText: '7 / 7',
    status: 'PENDING',
    updated: '18 min ago',
    actionText: 'Review',
  },
  {
    id: 'VR-2026-0077',
    sessionNumber: 'SN-2026-7721',
    instrument: 'Sansui Gold Balance',
    model: 'GoldMaster 6000',
    manufacturer: 'Sansui Electronics',
    accuracyClass: 'Class II',
    maxCapacity: '6000 g',
    interval: 'e = 0.1 g',
    procedure: 'Repeatability Test',
    progressText: '5 / 7',
    status: 'PASS',
    updated: '35 min ago',
    actionText: 'Continue',
  },
  {
    id: 'VR-2026-0044',
    sessionNumber: 'ES-2026-4418',
    instrument: 'Essae Heavy Bench',
    model: 'DS-215 Industrial',
    manufacturer: 'Essae-Teraoka',
    accuracyClass: 'Class IIII',
    maxCapacity: '150 kg',
    interval: 'e = 50 g',
    procedure: 'Statutory Sign-off',
    progressText: '7 / 7',
    status: 'PENDING',
    updated: '1h ago',
    actionText: 'View',
  },
  {
    id: 'VR-2026-0072',
    sessionNumber: 'AV-2026-7720',
    instrument: 'Avery ZM201 Retail',
    model: 'ZM201 Platform',
    manufacturer: 'Avery Weigh-Tronix',
    accuracyClass: 'Class III',
    maxCapacity: '30.000 kg',
    interval: 'e = 0.005 kg',
    procedure: 'Physical Inspection',
    progressText: '2 / 7',
    status: 'PASS',
    updated: '2h ago',
    actionText: 'Continue',
  },
];

export const INITIAL_COMPLIANCE: ComplianceData = {
  passRate: 94.2,
  passCount: 21,
  warningCount: 1,
  failCount: 2,
};

export const INSTRUMENT_PRESETS: InstrumentPreset[] = [
  {
    id: 'preset-avery',
    name: 'Avery Class III',
    brand: 'AVERY',
    classLabel: 'Class III Retail',
    model: 'ZM201 Retail Platform',
    manufacturer: 'Avery Weigh-Tronix',
    accuracyClass: 'CLASS_III',
    maxCapacity: '30 kg capacity',
    verificationInterval: 'e = 5 g',
    applicableTestsCount: 7,
    description: 'Medium accuracy commercial retail scale. OIML R 76-1 Clause 3.5.',
    tag: 'Retail Commercial',
  },
  {
    id: 'preset-mettler',
    name: 'Mettler Class I',
    brand: 'METTLER',
    classLabel: 'Class I Laboratory',
    model: 'XP205 Laboratory Balance',
    manufacturer: 'Mettler Toledo',
    accuracyClass: 'CLASS_I',
    maxCapacity: '120 g capacity',
    verificationInterval: 'e = 1 mg',
    applicableTestsCount: 8,
    description: 'Special accuracy precision micro-balance with draft shield protection.',
    tag: 'Analytical Precision',
  },
  {
    id: 'preset-sansui',
    name: 'Sansui Class II',
    brand: 'SANSUI',
    classLabel: 'Class II Gold Balance',
    model: 'GoldMaster 6000',
    manufacturer: 'Sansui Electronics',
    accuracyClass: 'CLASS_II',
    maxCapacity: '6000 g capacity',
    verificationInterval: 'e = 0.1 g',
    applicableTestsCount: 7,
    description: 'High accuracy jeweler & precious bullion verification balance.',
    tag: 'High Accuracy',
  },
  {
    id: 'preset-essae',
    name: 'Essae Class IIII',
    brand: 'ESSAE',
    classLabel: 'Class IIII Industrial',
    model: 'DS-215 Heavy Platform',
    manufacturer: 'Essae-Teraoka',
    accuracyClass: 'CLASS_IIII',
    maxCapacity: '150 kg capacity',
    verificationInterval: 'e = 50 g',
    applicableTestsCount: 6,
    description: 'Ordinary accuracy industrial bulk goods platform scale.',
    tag: 'Ordinary Freight',
  },
];

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: 'scenario-baseline',
    name: '1. Passing Baseline',
    subtitle: 'Standard Class III Compliant',
    expectedVerdict: 'PASS',
    classType: 'CLASS_III',
    description: 'Standard Avery Class III verification with full compliance.',
  },
  {
    id: 'scenario-rounding',
    name: '2. Rounding Discrepancy Trap',
    subtitle: 'Turning Point Interpolation (OIML 3.5.3.2)',
    expectedVerdict: 'PASS',
    classType: 'CLASS_III',
    description: 'Turning point formula P = I + 0.5e - delta L prevents false fail.',
  },
  {
    id: 'scenario-temperature',
    name: '3. Temperature Drift Failure',
    subtitle: 'Thermal Coefficient Out of Bounds',
    expectedVerdict: 'FAIL',
    classType: 'CLASS_II',
    description: 'Simulates ambient thermal gradient causing zero drift anomaly.',
  },
  {
    id: 'scenario-cantilever',
    name: '4. Eccentricity Cantilever Twist',
    subtitle: 'Corner 4 Mechanical Deflection',
    expectedVerdict: 'FAIL',
    classType: 'CLASS_III',
    description: 'Corner 4 deflection reveals error exceeding MPE limit.',
  },
  {
    id: 'scenario-micro',
    name: '5. Class I Micro-Precision',
    subtitle: 'Mettler XPR (120g / 1mg)',
    expectedVerdict: 'PASS',
    classType: 'CLASS_I',
    description: 'Microgram precision testing with buoyancy correction.',
  },
];
