import { JuryDemoStep } from './types';

export const JURY_DEMO_STEPS: JuryDemoStep[] = [
  {
    id: 'DEMO-01',
    stepNumber: 1,
    minuteMarker: '00:00',
    durationSeconds: 60,
    title: 'Problem & Platform Architecture',
    subtitle: 'Government Legal Metrology Automation',
    targetTab: 'dashboard',
    suggestedRole: 'Metrologist',
    scenarioId: 'scenario-baseline',
    scenarioName: 'Passing Baseline',
    showText: 'Operational Dashboard',
    focusAreas: ['Central LM Lab node status', '7-Stage verification pipeline', 'Live hardware scale bottom strip'],
    sayText: '“Today, legal metrology verification in India often relies on manual spreadsheets that lack tamper resistance and fail to catch mathematical edge cases. METROLOGIX-76 provides an end-to-end, OIML-certified platform with real-time statutory tolerance checking and cryptographic proof.”',
    keyHighlights: [
      'Automated statutory verification pipeline',
      'Real-time OIML R 76-1 compliance engine',
      'Role-based four-eyes governance architecture',
    ],
    statutoryReference: 'Legal Metrology (General) Rules, 2011 & OIML R 76-1',
    statutoryDetail: 'Rule 27 stipulates the official verification procedure conforming to Seventh Schedule specifications, requiring unbroken traceability from physical intake to digital certification.',
  },
  {
    id: 'DEMO-02',
    stepNumber: 2,
    minuteMarker: '01:00',
    durationSeconds: 60,
    title: 'Instrument Intake & Parameter Validation',
    subtitle: 'TAC & Specification Extraction',
    targetTab: 'intake',
    suggestedRole: 'Metrologist',
    scenarioId: 'scenario-baseline',
    scenarioName: 'Passing Baseline',
    showText: 'Instrument Intake & Registration',
    focusAreas: ['Scale division count n = Max / e', 'Type Approval Certificate (TAC) validation', 'Class III Accuracy Classification'],
    sayText: '“When an instrument arrives at the laboratory, we compute scale divisions and verify conformity with its Type Approval Certificate. For this Avery ZM201, Max = 30 kg and e = 0.005 kg yields exactly 6,000 divisions, placing it strictly in Class III.”',
    keyHighlights: [
      'Automated scale division calculation (n = Max / e)',
      'Type Approval Certificate verification',
      'Statutory Class III threshold conformance',
    ],
    statutoryReference: 'OIML R 76-1 Section 3.2 (Accuracy Classes) & Rule 27',
    statutoryDetail: 'Class III Non-Automatic Weighing Instruments require between 500 and 10,000 verification scale intervals. Discrepancies trigger automated intake rejections.',
  },
  {
    id: 'DEMO-03',
    stepNumber: 3,
    minuteMarker: '02:00',
    durationSeconds: 60,
    title: 'Standards Traceability & Lockout Gate',
    subtitle: 'Unbroken Chain of Traceability',
    targetTab: 'standards',
    suggestedRole: 'Metrologist',
    scenarioId: 'scenario-baseline',
    scenarioName: 'Passing Baseline',
    showText: 'Standards & Traceability Ledger',
    focusAreas: ['E2, F1, M1 reference weight countdowns', 'Global Hard Testing Lockout Banner', 'NPL & RRSL calibration certificates'],
    sayText: '“A verification test is legally invalid if the reference weights are out of calibration. METROLOGIX-76 enforces an automated lockout: if a standard weight set expires, all input across test screens is instantly frozen, preventing fraudulent post-dated testing.”',
    keyHighlights: [
      'Unbroken metrological traceability chain',
      'Automated hard testing lockout on expired standards',
      'NPL and Regional Laboratory certificate linkage',
    ],
    statutoryReference: 'OIML R 111-1 & ISO/IEC 17025 § 6.4 (Equipment)',
    statutoryDetail: 'Working standard weights must possess valid calibration certificates traceable to primary National Physical Laboratory (NPL) standards.',
  },
  {
    id: 'DEMO-04',
    stepNumber: 4,
    minuteMarker: '03:00',
    durationSeconds: 60,
    title: 'Physical Inspection & Security Seals',
    subtitle: 'Visual, Spirit Level & Tamper Audit',
    targetTab: 'physical_inspection',
    suggestedRole: 'Metrologist',
    scenarioId: 'scenario-baseline',
    scenarioName: 'Passing Baseline',
    showText: 'Physical Pre-test Inspection',
    focusAreas: ['Interactive spirit-level bubble centering', 'Lead-wire, hologram & jumper seal checklist', 'Optical photographic evidence capture'],
    sayText: '“Before placing weights, the officer inspects physical integrity. Our interactive spirit level verifies horizontal alignment, and optical photo capture audits the lead-wire seal to ensure the calibration jumper has not been tampered with.”',
    keyHighlights: [
      'Interactive spirit-level bubble centering',
      'Lead-wire, hologram & calibration jumper audit',
      'Photographic tamper evidence capture',
    ],
    statutoryReference: 'WELMEC 7.2 Guide & Legal Metrology Act § 24',
    statutoryDetail: 'Physical pre-test gate guarantees that the weighing instrument is installed horizontally level and tamper seals are uncompromised before load testing.',
  },
  {
    id: 'DEMO-05',
    stepNumber: 5,
    minuteMarker: '04:00',
    durationSeconds: 90,
    title: 'Automated Weighing Test & Error Corridor',
    subtitle: 'Turning-Point Formula & Statutory MPE',
    targetTab: 'weighing_linearity',
    suggestedRole: 'Metrologist',
    scenarioId: 'scenario-rounding',
    scenarioName: 'Rounding Discrepancy Trap',
    showText: 'Weighing Error & Linearity Test',
    focusAreas: ['Observation Grid with turning point formula', 'Continuous Error Corridor Chart (±1e, ±2e, ±3e)', 'False Pass Detection vs Digital Fail'],
    sayText: '“Instead of integer display rounding, we apply additional weights ΔL to find the exact turning point. The system dynamically plots error corridors. Where legacy spreadsheets falsely reported PASS, our turning-point analysis detects continuous error exceeding statutory MPE.”',
    keyHighlights: [
      'Turning-point error calculation: P = I + 0.5e - ΔL',
      'Continuous legal tolerance corridors',
      'Instant detection of rounding-concealed failures',
    ],
    statutoryReference: 'OIML R 76-1 Section 3.5.1 (Table 6 MPE) & Section 3.5.3.2',
    statutoryDetail: 'Error E = P - L, where P is the true indication before rounding. Maximum Permissible Error (MPE) for Class III scales is ±0.5e, ±1.0e, or ±1.5e depending on test load.',
  },
  {
    id: 'DEMO-06',
    stepNumber: 6,
    minuteMarker: '05:30',
    durationSeconds: 60,
    title: 'Eccentricity & Repeatability Testing',
    subtitle: 'Corner Loading Geometry & 10 Runs',
    targetTab: 'eccentricity_workspace',
    suggestedRole: 'Metrologist',
    scenarioId: 'scenario-cantilever',
    scenarioName: 'Eccentricity Cantilever Twist',
    showText: 'Eccentricity / Corner Loading',
    focusAreas: ['Interactive SVG platter corner deflection', 'Worst corner deviation vector (Corner 4)', '10-Run repeatability consistency check'],
    sayText: '“Eccentricity tests verify that off-center load placement does not introduce illegal bias. Our SVG platter visually maps corner deflection vectors and automatically flags when off-center error exceeds maximum permissible limits.”',
    keyHighlights: [
      'Interactive SVG platter corner mapping',
      'Worst deflection hotspot detection (Corner 4 deflection)',
      '10-Run repeatability drift validation',
    ],
    statutoryReference: 'OIML R 76-1 Section 3.6.1 (Repeatability) & 3.6.2 (Eccentricity)',
    statutoryDetail: 'Load of 1/3 to 1/2 Max placed at positions 1, 2, 3, 4 and center. The error at any corner must not exceed the MPE for that test load.',
  },
  {
    id: 'DEMO-07',
    stepNumber: 7,
    minuteMarker: '06:30',
    durationSeconds: 60,
    title: 'Live Hardware / IoT Scale Bridge',
    subtitle: 'Direct Serial Stream & WELMEC 7.2',
    targetTab: 'scale_bridge',
    suggestedRole: 'Metrologist',
    scenarioId: 'scenario-baseline',
    scenarioName: 'Passing Baseline',
    showText: 'IoT Scale Bridge & Protocol Terminal',
    focusAreas: ['7-Segment IBM Plex Mono live weight display', 'Cryptographic Stable/Unstable reading gate', 'WELMEC 7.2 software examination card (C: 12, P: 08)'],
    sayText: '“METROLOGIX-76 connects directly to weighing hardware via RS-232 / USB serial protocols or our built-in simulator. It captures readings only when scale stability is cryptographically affirmed, and executes automated WELMEC 7.2 software examinations.”',
    keyHighlights: [
      'RS-232 / USB serial stream & virtual simulator',
      'Certified stable-reading gate before observation commit',
      'WELMEC 7.2 firmware hash & audit counter examination',
    ],
    statutoryReference: 'WELMEC 7.2 Guide (Software Requirements on Measuring Instruments)',
    statutoryDetail: 'Enforces software separation, legibility of calibration counter C and parameter counter P, and immutable firmware checksum verification.',
  },
  {
    id: 'DEMO-08',
    stepNumber: 8,
    minuteMarker: '07:30',
    durationSeconds: 60,
    title: 'Legacy Excel Ingestion & Flaw Auditor',
    subtitle: 'Forensic Detection of Historical False Passes',
    targetTab: 'excel_auditor',
    suggestedRole: 'Metrologist',
    scenarioId: 'scenario-rounding',
    scenarioName: 'Rounding Discrepancy Trap',
    showText: 'Legacy Excel Auditor',
    focusAreas: ['Drag-and-drop .xlsx dropzone', 'Hero Rounding Discrepancy Card (Row 17)', 'Side-by-side recalculation comparison table'],
    sayText: '“Here is our forensic differentiator: we ingest historical Excel spreadsheets and recompute every formula against OIML algorithms. We immediately flag historical false passes where scales failed statutory limits but were certified due to spreadsheet rounding truncations.”',
    keyHighlights: [
      'Multi-tab .xlsx parsing & formula recalculation',
      'Forensic detection of historical false passes',
      'Side-by-side mathematical proof: Legacy PASS vs Digital FAIL',
    ],
    statutoryReference: 'WELMEC 7.2 § 4.3 & Legal Metrology Act § 15',
    statutoryDetail: 'Forensic re-evaluation of historical verification records to eliminate spreadsheet rounding artifacts, truncation errors, and unauthorized manual overrides.',
  },
  {
    id: 'DEMO-09',
    stepNumber: 9,
    minuteMarker: '08:30',
    durationSeconds: 45,
    title: 'Statutory Peer Review & Exceptions',
    subtitle: 'Independent Four-Eyes Principle Review',
    targetTab: 'review',
    suggestedRole: 'Reviewer',
    scenarioId: 'scenario-rounding',
    scenarioName: 'Rounding Discrepancy Trap',
    showText: 'Statutory Review & Peer Sign-Off',
    focusAreas: ['7-Stage test evidence audit dossier', 'Automated statutory compliance findings', 'Mandatory remand justification modal'],
    sayText: '“In accordance with ISO 17020 four-eyes principles, the testing officer cannot approve their own verification. A senior reviewer audits the full evidence dossier, inspects tolerance graphs, and approves or remands with mandatory statutory reasoning.”',
    keyHighlights: [
      'Strict separation of duties (Four-Eyes Principle)',
      '7-Stage test evidence audit dossier',
      'Mandatory legal justification on remand or rejection',
    ],
    statutoryReference: 'ISO/IEC 17020 § 7.4 & Legal Metrology Verification Framework',
    statutoryDetail: 'Statutory verification governance demands independent peer review to ensure all metrological observations conform to statutory tolerances before final certification.',
  },
  {
    id: 'DEMO-10',
    stepNumber: 10,
    minuteMarker: '09:15',
    durationSeconds: 45,
    title: 'Director Sign-Off & Guilloche Seal',
    subtitle: 'Cryptographic Authorization & PIN Gate',
    targetTab: 'review',
    suggestedRole: 'Director',
    scenarioId: 'scenario-baseline',
    scenarioName: 'Passing Baseline',
    showText: 'Director Authorization & Cryptographic Sign',
    focusAreas: ['Director 4-digit PIN authentication (1947)', 'Green Guilloche anti-counterfeit seal preview', 'SHA-256 digital certificate signature digest'],
    sayText: '“Only the authorized Director can apply the statutory seal. With their 4-digit PIN and legal declaration, the certificate is cryptographically locked with an anti-counterfeit green Guilloche seal and becomes permanently tamper-proof.”',
    keyHighlights: [
      'Director PIN authorization gate (PIN: 1947)',
      'Anti-counterfeit Green Guilloche statutory seal',
      'Immutable SHA-256 digital signature digest',
    ],
    statutoryReference: 'Information Technology Act, 2000 § 3A & Rule 16',
    statutoryDetail: 'Digital signature and secure authentication create statutory non-repudiation and cryptographic validity under the Indian IT Act and Legal Metrology Rules.',
  },
  {
    id: 'DEMO-11',
    stepNumber: 11,
    minuteMarker: '09:45',
    durationSeconds: 30,
    title: 'Certificate Repository & e-Māap QR',
    subtitle: 'Official Form VI & Public Verification',
    targetTab: 'reports',
    suggestedRole: 'Auditor',
    scenarioId: 'scenario-baseline',
    scenarioName: 'Passing Baseline',
    showText: 'Bilingual Certificate Repository',
    focusAreas: ['Form VI Bilingual Certificate (English/Hindi)', 'National e-Māap QR portal verification', 'Cryptographic SHA-256 audit ledger link'],
    sayText: '“The approved verification generates statutory Form VI with an embedded e-Māap QR code. Any field inspector or consumer can scan it to confirm validity, backed by an immutable SHA-256 audit ledger that visibly breaks if altered.”',
    keyHighlights: [
      'Bilingual Form VI Verification Certificate',
      'Consumer e-Māap QR portal verification',
      'Immutable SHA-256 hash-chain audit ledger',
    ],
    statutoryReference: 'National e-Māap Portal & Form VI (Rule 24)',
    statutoryDetail: 'Legal Metrology Certificate Form VI issued under Rule 24, backed by public cryptographic verification via the national e-Māap digital portal.',
  },
];
