export type SessionTestingStatus =
  | 'IN_TESTING'
  | 'ACTION_REQUIRED'
  | 'PAUSED'
  | 'PENDING_REVIEW'
  | 'APPROVED'
  | 'REMANDED';

export interface ActiveSessionItem {
  id: string; // e.g. 'SES-2026-0041'
  sessionNumber: string; // e.g. 'SES-2026-0041'
  manufacturer: string;
  model: string;
  serialNumber: string; // e.g. 'AV-2026-8812'
  accuracyClass: 'Class I' | 'Class II' | 'Class III' | 'Class IIII';
  maxCapacity: string; // e.g. '30 kg'
  maxCapacityKg: number;
  interval: string; // e.g. 'e = 5 g'
  verificationStage: 'Initial Type Approval' | 'Subsequent Verification' | 'In-Service Inspection';
  currentStep: number; // 1 to 7
  currentStepCode?: string; // e.g. '03'
  currentTestName: string; // e.g. 'Weighing Error & Linearity'
  totalSteps: number; // 7
  progressPercent: number; // e.g. 43
  status: SessionTestingStatus;
  issueDescription?: string;
  flagReason?: string; // e.g. 'Reviewer flagged: Observation #7'
  remandReason?: string; // e.g. 'Eccentricity observation requires re-check.'
  certificateNumber?: string; // e.g. 'CERT-2026-00192'
  lastSaved: string; // e.g. '4 min ago'
  startedAt?: string; // e.g. '02 Oct 2026, 10:42'
  operatorName: string;
  targetView: string;
}

export const INITIAL_ACTIVE_SESSIONS: ActiveSessionItem[] = [
  {
    id: 'SES-2026-0041',
    sessionNumber: 'SES-2026-0041',
    serialNumber: 'AV-2026-8812',
    manufacturer: 'Avery Weigh-Tronix',
    model: 'Avery ZM201 Retail',
    accuracyClass: 'Class III',
    maxCapacity: '30 kg',
    maxCapacityKg: 30.0,
    interval: 'e = 5 g',
    verificationStage: 'Initial Type Approval',
    currentStep: 3,
    currentStepCode: '03',
    currentTestName: 'Weighing Error & Linearity',
    totalSteps: 7,
    progressPercent: 43,
    status: 'IN_TESTING',
    lastSaved: '4 min ago',
    startedAt: '02 Oct 2026, 10:42',
    operatorName: 'Rahul Kumar',
    targetView: 'weighing_linearity',
  },
  {
    id: 'SES-2026-0042',
    sessionNumber: 'SES-2026-0042',
    serialNumber: 'MT-2026-1042',
    manufacturer: 'Mettler Toledo',
    model: 'Mettler XPR 120 Analytical',
    accuracyClass: 'Class I',
    maxCapacity: '120 g',
    maxCapacityKg: 0.12,
    interval: 'e = 1 mg',
    verificationStage: 'Initial Type Approval',
    currentStep: 7,
    currentStepCode: '07',
    currentTestName: 'Statutory Review & Sign-Off',
    totalSteps: 7,
    progressPercent: 100,
    status: 'PENDING_REVIEW',
    lastSaved: '18 min ago',
    startedAt: '01 Oct 2026, 14:15',
    operatorName: 'P. Deshmukh',
    targetView: 'review_workspace',
  },
  {
    id: 'SES-2026-0043',
    sessionNumber: 'SES-2026-0043',
    serialNumber: 'SN-2026-7721',
    manufacturer: 'Sansui Electronics',
    model: 'Sansui Gold Balance 600',
    accuracyClass: 'Class II',
    maxCapacity: '6000 g',
    maxCapacityKg: 6.0,
    interval: 'e = 0.1 g',
    verificationStage: 'Initial Type Approval',
    currentStep: 5,
    currentStepCode: '05',
    currentTestName: 'Repeatability Test (Run 06)',
    totalSteps: 7,
    progressPercent: 71,
    status: 'IN_TESTING',
    lastSaved: '35 min ago',
    startedAt: '03 Oct 2026, 09:30',
    operatorName: 'Rahul Kumar',
    targetView: 'repeatability_workspace',
  },
  {
    id: 'SES-2026-0044',
    sessionNumber: 'SES-2026-0044',
    serialNumber: 'ES-2026-4418',
    manufacturer: 'Essae-Teraoka',
    model: 'Essae Platform Pro 150',
    accuracyClass: 'Class IIII',
    maxCapacity: '150 kg',
    maxCapacityKg: 150.0,
    interval: 'e = 50 g',
    verificationStage: 'Subsequent Verification',
    currentStep: 7,
    currentStepCode: '07',
    currentTestName: 'Verification Completed',
    totalSteps: 7,
    progressPercent: 100,
    status: 'APPROVED',
    certificateNumber: 'CERT-2026-00192',
    lastSaved: 'Yesterday',
    startedAt: '28 Sep 2026, 11:00',
    operatorName: 'V. K. Menon',
    targetView: 'review_workspace',
  },
  {
    id: 'SES-2026-0045',
    sessionNumber: 'SES-2026-0045',
    serialNumber: 'AV-2026-7720',
    manufacturer: 'Avery Weigh-Tronix',
    model: 'Avery Retail Counter',
    accuracyClass: 'Class III',
    maxCapacity: '15 kg',
    maxCapacityKg: 15.0,
    interval: 'e = 2 g',
    verificationStage: 'In-Service Inspection',
    currentStep: 2,
    currentStepCode: '02',
    currentTestName: 'Eccentricity & Corner Load',
    totalSteps: 7,
    progressPercent: 28,
    status: 'REMANDED',
    remandReason: 'Eccentricity observation requires re-check.',
    issueDescription: 'Eccentricity observation requires re-check.',
    lastSaved: '2h ago',
    startedAt: '02 Oct 2026, 16:20',
    operatorName: 'A. Verma',
    targetView: 'eccentricity_workspace',
  },
  {
    id: 'SES-2026-0046',
    sessionNumber: 'SES-2026-0046',
    serialNumber: 'ET-2026-9041',
    manufacturer: 'Essae-Teraoka',
    model: 'Essae Heavy Platform',
    accuracyClass: 'Class IIII',
    maxCapacity: '150 kg',
    maxCapacityKg: 150.0,
    interval: 'e = 50 g',
    verificationStage: 'Subsequent Verification',
    currentStep: 4,
    currentStepCode: '04',
    currentTestName: 'Eccentricity (Corner C)',
    totalSteps: 7,
    progressPercent: 57,
    status: 'ACTION_REQUIRED',
    flagReason: 'Reviewer flagged: Observation #7',
    issueDescription: 'Corner C exceeds configured tolerance (+65 g vs limit ±50 g).',
    lastSaved: '31 min ago',
    startedAt: '03 Oct 2026, 11:15',
    operatorName: 'A. Verma',
    targetView: 'eccentricity_workspace',
  },
  {
    id: 'SES-2026-0047',
    sessionNumber: 'SES-2026-0047',
    serialNumber: 'MT-2026-0049',
    manufacturer: 'Mettler Toledo',
    model: 'Mettler XP205 Micro-Balance',
    accuracyClass: 'Class I',
    maxCapacity: '220 g',
    maxCapacityKg: 0.22,
    interval: 'e = 1 mg',
    verificationStage: 'Initial Type Approval',
    currentStep: 6,
    currentStepCode: '06',
    currentTestName: 'Climatic Drift & Temperature',
    totalSteps: 7,
    progressPercent: 86,
    status: 'IN_TESTING',
    lastSaved: '14 min ago',
    startedAt: '04 Oct 2026, 08:30',
    operatorName: 'P. Deshmukh',
    targetView: 'environmental_workspace',
  },
  {
    id: 'SES-2026-0048',
    sessionNumber: 'SES-2026-0048',
    serialNumber: 'SA-2026-1092',
    manufacturer: 'Sartorius AG',
    model: 'Cubis II High-Precision',
    accuracyClass: 'Class I',
    maxCapacity: '120 g',
    maxCapacityKg: 0.12,
    interval: 'e = 0.1 mg',
    verificationStage: 'Initial Type Approval',
    currentStep: 7,
    currentStepCode: '07',
    currentTestName: 'Supervisory Peer Review',
    totalSteps: 7,
    progressPercent: 100,
    status: 'PENDING_REVIEW',
    lastSaved: '1 hr ago',
    startedAt: '03 Oct 2026, 15:40',
    operatorName: 'P. Deshmukh',
    targetView: 'review_workspace',
  },
  {
    id: 'SES-2026-0049',
    sessionNumber: 'SES-2026-0049',
    serialNumber: 'AV-2026-5120',
    manufacturer: 'Avery Weigh-Tronix',
    model: 'ZM305 Washdown Scale',
    accuracyClass: 'Class III',
    maxCapacity: '60 kg',
    maxCapacityKg: 60.0,
    interval: 'e = 0.01 kg',
    verificationStage: 'Subsequent Verification',
    currentStep: 3,
    currentStepCode: '03',
    currentTestName: 'Weighing Error (Ascending)',
    totalSteps: 7,
    progressPercent: 43,
    status: 'IN_TESTING',
    lastSaved: '3 hrs ago',
    startedAt: '04 Oct 2026, 07:15',
    operatorName: 'Rahul Kumar',
    targetView: 'weighing_linearity',
  },
  {
    id: 'SES-2026-0050',
    sessionNumber: 'SES-2026-0050',
    serialNumber: 'SN-2026-0182',
    manufacturer: 'Sansui Electronics',
    model: 'LabPro 3000 Standard',
    accuracyClass: 'Class II',
    maxCapacity: '3.0 kg',
    maxCapacityKg: 3.0,
    interval: 'e = 0.05 g',
    verificationStage: 'Initial Type Approval',
    currentStep: 7,
    currentStepCode: '07',
    currentTestName: 'Verification Completed',
    totalSteps: 7,
    progressPercent: 100,
    status: 'APPROVED',
    certificateNumber: 'CERT-2026-00172',
    lastSaved: '2 days ago',
    startedAt: '25 Sep 2026, 09:00',
    operatorName: 'V. K. Menon',
    targetView: 'review_workspace',
  },
  {
    id: 'SES-2026-0051',
    sessionNumber: 'SES-2026-0051',
    serialNumber: 'ET-2026-4402',
    manufacturer: 'Essae-Teraoka',
    model: 'FB-500 Precision Bench',
    accuracyClass: 'Class III',
    maxCapacity: '15 kg',
    maxCapacityKg: 15.0,
    interval: 'e = 2 g',
    verificationStage: 'In-Service Inspection',
    currentStep: 1,
    currentStepCode: '01',
    currentTestName: 'Visual & Markings Inspection',
    totalSteps: 7,
    progressPercent: 14,
    status: 'IN_TESTING',
    lastSaved: '5 hrs ago',
    startedAt: '04 Oct 2026, 06:45',
    operatorName: 'A. Verma',
    targetView: 'physical_inspection',
  },
  {
    id: 'SES-2026-0052',
    sessionNumber: 'SES-2026-0052',
    serialNumber: 'SN-2026-3391',
    manufacturer: 'Sansui Electronics',
    model: 'GoldMaster 600 Precision',
    accuracyClass: 'Class II',
    maxCapacity: '600 g',
    maxCapacityKg: 0.6,
    interval: 'e = 0.01 g',
    verificationStage: 'Initial Type Approval',
    currentStep: 5,
    currentStepCode: '05',
    currentTestName: 'Repeatability Test (Run 06)',
    totalSteps: 7,
    progressPercent: 71,
    status: 'PAUSED',
    issueDescription: 'Awaiting thermal stabilization chamber availability.',
    lastSaved: '45 min ago',
    startedAt: '03 Oct 2026, 13:00',
    operatorName: 'Rahul Kumar',
    targetView: 'repeatability_workspace',
  },
];
