import { ReviewSessionCase } from './types';

export const INITIAL_REVIEW_CASES: ReviewSessionCase[] = [
  {
    id: 'VR-2026-00417',
    sessionNumber: 'VR-2026-00417',
    manufacturer: 'Mettler-Toledo',
    model: 'XPR Analytical Micro-Balance',
    serialNumber: 'MT-2026-0049',
    accuracyClass: 'Class I',
    maxCapacity: '120 g',
    interval: 'e = 0.001 g',
    verificationStage: 'Initial Type Approval',
    completedSteps: 7,
    totalSteps: 7,
    status: 'PENDING_REVIEW',
    overallVerdict: 'PASS',
    updatedAt: '18 min ago',
    tests: [
      {
        id: 'test-phys',
        name: 'Physical Inspection & Security Audit',
        code: 'OIML R 76-1 Section 3.1 & 4.1',
        status: 'PASS',
        summary: 'All required checks passed',
        detail: 'Lead-wire tamper seal intact, optical level bubble centered (< 0.2°), nameplate stamped, dual calibration jumpers secured.',
        observationsCount: '5 / 5 statutory items verified',
        targetView: 'physical_inspection',
      },
      {
        id: 'test-weigh',
        name: 'Weighing Error & Linearity',
        code: 'OIML R 76-1 Section 3.5.1',
        status: 'PASS',
        summary: '14 / 14 observations complete',
        detail: 'Both ascending and descending series evaluated to 100% Max capacity. Max hysteresis 0.28e, maximum turning-point error within ±0.5e MPE band.',
        observationsCount: '14 load points (0.5e MPE)',
        targetView: 'weighing_linearity',
      },
      {
        id: 'test-ecc',
        name: 'Eccentricity (Corner Loading)',
        code: 'OIML R 76-1 Section 3.6.2',
        status: 'MARGINAL',
        summary: 'Corner C near permissible limit',
        detail: 'Corner C showed +0.0004 g deviation at 1/3 Max load against ±0.0005 g statutory limit (80% boundary alert triggered). All other corners within 40% band.',
        observationsCount: '5 platter positions evaluated',
        targetView: 'eccentricity_workspace',
      },
      {
        id: 'test-rep',
        name: 'Repeatability Test',
        code: 'OIML R 76-1 Section 3.6.1',
        status: 'PASS',
        summary: 'Spread within limit',
        detail: '10 sequential cycles at 0.8 Max (96 g). Range Δ = E_max - E_min = 0.0003 g (allowable limit = 0.0005 g). Zero-return verified on every unload.',
        observationsCount: '10 consecutive cycles verified',
        targetView: 'repeatability_workspace',
      },
      {
        id: 'test-env',
        name: 'Environmental Drift & Tare Testing',
        code: 'OIML R 76-1 Section 3.5.3.3 & 3.9',
        status: 'PASS',
        summary: 'All configured checks passed',
        detail: 'Additive and subtractive tare error ≤ 0.25e. Temperature sequence (+20°C → +40°C → -10°C → +20°C) completed with zero drift < 0.2e / 5K.',
        observationsCount: 'Tare + 4-point thermal corridor',
        targetView: 'environmental_workspace',
      },
    ],
    findings: [
      {
        id: 'finding-1',
        observationIndex: 'Observation #07',
        testName: 'Weighing • Ascending Series (100 g)',
        severity: 'FLAG',
        title: 'Low margin warning',
        author: 'R. Kumar • Technical Reviewer',
        text: 'Observed error (+0.00042 g) approaches the configured tolerance boundary (±0.00050 g). While compliant under OIML 3.5.1, recommended for re-verification interval note.',
        timestamp: '04 Oct 2026 • 15:31',
        resolved: false,
      },
      {
        id: 'finding-2',
        observationIndex: 'Observation #04',
        testName: 'Eccentricity • Corner C Loading',
        severity: 'NOTE',
        title: 'Calibration standard cross-check',
        author: 'R. Kumar • Technical Reviewer',
        text: 'Class E1 standard set STD-E1-01 verified with zero buoyancy anomaly before eccentricity test execution.',
        timestamp: '04 Oct 2026 • 15:28',
        resolved: true,
      },
    ],
    auditTrail: [
      {
        id: 'audit-1',
        time: '15:12',
        iconType: 'complete',
        action: 'Environmental drift & tare test completed',
        actor: 'S. Sharma (Metrologist)',
      },
      {
        id: 'audit-2',
        time: '15:24',
        iconType: 'forward',
        action: 'Submitted test dossier for supervisory review',
        actor: 'S. Sharma (Metrologist)',
      },
      {
        id: 'audit-3',
        time: '15:29',
        iconType: 'open',
        action: 'Reviewer opened session case file',
        actor: 'R. Kumar (Technical Reviewer)',
      },
      {
        id: 'audit-4',
        time: '15:31',
        iconType: 'flag',
        action: 'Observation #07 flagged for margin review',
        actor: 'R. Kumar (Technical Reviewer)',
      },
    ],
  },
  {
    id: 'VR-2026-00416',
    sessionNumber: 'VR-2026-00416',
    manufacturer: 'Essae-Teraoka',
    model: 'DS-215 Heavy Platform',
    serialNumber: 'ET-2026-9041',
    accuracyClass: 'Class IIII',
    maxCapacity: '150 kg',
    interval: 'e = 50 g',
    verificationStage: 'Subsequent Verification',
    completedSteps: 3,
    totalSteps: 7,
    status: 'REMANDED',
    overallVerdict: 'FAIL',
    updatedAt: '31 min ago',
    remandReason: 'Corner C eccentricity deviation (+42 g) exceeds maximum permissible error limit (±25 g). Platter load cell mechanical mounting requires inspection, levelling realignment, and full test re-execution.',
    remandedBy: 'R. Kumar • Technical Reviewer',
    remandDate: '04 Oct 2026 • 14:15 IST',
    tests: [
      {
        id: 'test-phys-16',
        name: 'Physical Inspection & Security Audit',
        code: 'OIML R 76-1 Section 3.1 & 4.1',
        status: 'PASS',
        summary: 'All required checks passed',
        detail: 'Hardware enclosure intact, heavy duty platform stable.',
        observationsCount: '5 / 5 verified',
        targetView: 'physical_inspection',
      },
      {
        id: 'test-weigh-16',
        name: 'Weighing Error & Linearity',
        code: 'OIML R 76-1 Section 3.5.1',
        status: 'PASS',
        summary: 'Linearity completed within MPE',
        detail: 'Tolerance compliance verified up to 150 kg.',
        observationsCount: '10 load points',
        targetView: 'weighing_linearity',
      },
      {
        id: 'test-ecc-16',
        name: 'Eccentricity (Corner Loading)',
        code: 'OIML R 76-1 Section 3.6.2',
        status: 'FAIL',
        summary: 'Corner C exceeded permissible tolerance',
        detail: 'Reading +42 g vs allowable limit ±25 g at 50 kg test load. Statutory violation detected.',
        observationsCount: 'Corner C Out of Bounds',
        targetView: 'eccentricity_workspace',
      },
    ],
    findings: [
      {
        id: 'finding-16-1',
        observationIndex: 'Corner C Deflection',
        testName: 'Eccentricity',
        severity: 'BLOCKER',
        title: 'Statutory Tolerance Exceeded',
        author: 'R. Kumar • Technical Reviewer',
        text: 'Eccentricity test corner C exceeds maximum permissible error (42 g > 25 g). Session must be remanded to testing engineer for mechanical re-alignment.',
        timestamp: '04 Oct 2026 • 14:12',
        resolved: false,
      },
    ],
    auditTrail: [
      {
        id: 'audit-16-1',
        time: '13:50',
        iconType: 'complete',
        action: 'Eccentricity test failed at Corner C',
        actor: 'M. Patel (Metrologist)',
      },
      {
        id: 'audit-16-2',
        time: '14:15',
        iconType: 'remand',
        action: 'Case remanded with mandatory justification',
        actor: 'R. Kumar (Technical Reviewer)',
      },
    ],
  },
  {
    id: 'VR-2026-00415',
    sessionNumber: 'VR-2026-00415',
    manufacturer: 'Avery Weigh-Tronix',
    model: 'ZM201 Retail Platform',
    serialNumber: 'AV-2026-8812',
    accuracyClass: 'Class III',
    maxCapacity: '30 kg',
    interval: 'e = 0.005 kg',
    verificationStage: 'Initial Type Approval',
    completedSteps: 7,
    totalSteps: 7,
    status: 'PENDING_REVIEW',
    overallVerdict: 'PASS',
    updatedAt: '1 hr ago',
    tests: [
      {
        id: 'test-phys-15',
        name: 'Physical Inspection & Security Audit',
        code: 'OIML R 76-1 Section 3.1 & 4.1',
        status: 'PASS',
        summary: 'All required checks passed',
        detail: 'Seals and spirit level verified.',
        observationsCount: '5 / 5 verified',
        targetView: 'physical_inspection',
      },
      {
        id: 'test-weigh-15',
        name: 'Weighing Error & Linearity',
        code: 'OIML R 76-1 Section 3.5.1',
        status: 'PASS',
        summary: 'Full range within 0.5e MPE',
        detail: 'Ascending and descending runs compliant.',
        observationsCount: '12 load points',
        targetView: 'weighing_linearity',
      },
      {
        id: 'test-ecc-15',
        name: 'Eccentricity (Corner Loading)',
        code: 'OIML R 76-1 Section 3.6.2',
        status: 'PASS',
        summary: 'All 5 positions within tolerance',
        detail: 'Max deviation 0.002 kg vs 0.005 kg limit.',
        observationsCount: '5 points verified',
        targetView: 'eccentricity_workspace',
      },
      {
        id: 'test-rep-15',
        name: 'Repeatability Test',
        code: 'OIML R 76-1 Section 3.6.1',
        status: 'PASS',
        summary: 'Spread within limit',
        detail: 'Δ = 0.003 kg vs 0.005 kg allowable.',
        observationsCount: '10 cycles verified',
        targetView: 'repeatability_workspace',
      },
      {
        id: 'test-env-15',
        name: 'Environmental Drift & Tare Testing',
        code: 'OIML R 76-1 Section 3.5.3.3 & 3.9',
        status: 'PASS',
        summary: 'Thermal coefficient compliant',
        detail: 'Tare error < 0.25e.',
        observationsCount: 'Tare + drift verified',
        targetView: 'environmental_workspace',
      },
    ],
    findings: [],
    auditTrail: [
      {
        id: 'audit-15-1',
        time: '14:20',
        iconType: 'complete',
        action: 'All 7 test stages completed',
        actor: 'S. Sharma (Metrologist)',
      },
      {
        id: 'audit-15-2',
        time: '14:35',
        iconType: 'forward',
        action: 'Submitted for peer review',
        actor: 'S. Sharma (Metrologist)',
      },
    ],
  },
  {
    id: 'VR-2026-00414',
    sessionNumber: 'VR-2026-00414',
    manufacturer: 'Sansui Electronics',
    model: 'GoldMaster 6000 Precision',
    serialNumber: 'SN-2026-3391',
    accuracyClass: 'Class II',
    maxCapacity: '6,000 g',
    interval: 'e = 0.1 g',
    verificationStage: 'Initial Type Approval',
    completedSteps: 7,
    totalSteps: 7,
    status: 'APPROVED',
    overallVerdict: 'PASS',
    updatedAt: '04 Oct 2026 • 16:02',
    certificate: {
      id: 'CERT-2026-00172',
      signedBy: 'Dr. S. Sharma',
      signedRole: 'Laboratory Director, Central LM Laboratory',
      signTimestamp: '04 Oct 2026 • 16:02 IST',
      sha256Digest: '8d72f1c3a9689e47b01dc1f0e27ba61e9b6238f9024cf4f87ab2e105e19db621',
      verificationUrl: 'https://metrologix.gov.in/verify/CERT-2026-00172',
      qrPayload: 'METROLOGIX-76|CERT-2026-00172|SANSUI-GM6000|SN-2026-3391|CLASS-II|VERIFIED-PASS|2026-10-04T16:02:00IST',
      directorPinUsed: '7620',
    },
    tests: [
      {
        id: 'test-phys-14',
        name: 'Physical Inspection & Security Audit',
        code: 'OIML R 76-1 Section 3.1 & 4.1',
        status: 'PASS',
        summary: 'All required checks passed',
        detail: 'Approved and sealed.',
        observationsCount: '5 / 5 verified',
        targetView: 'physical_inspection',
      },
      {
        id: 'test-weigh-14',
        name: 'Weighing Error & Linearity',
        code: 'OIML R 76-1 Section 3.5.1',
        status: 'PASS',
        summary: 'Linearity certified',
        detail: 'Full span compliant.',
        observationsCount: '12 points verified',
        targetView: 'weighing_linearity',
      },
      {
        id: 'test-ecc-14',
        name: 'Eccentricity (Corner Loading)',
        code: 'OIML R 76-1 Section 3.6.2',
        status: 'PASS',
        summary: 'Corner loading certified',
        detail: 'Compliant across all positions.',
        observationsCount: '5 positions verified',
        targetView: 'eccentricity_workspace',
      },
      {
        id: 'test-rep-14',
        name: 'Repeatability Test',
        code: 'OIML R 76-1 Section 3.6.1',
        status: 'PASS',
        summary: 'Repeatability certified',
        detail: 'Spread within 0.05 g limit.',
        observationsCount: '10 cycles verified',
        targetView: 'repeatability_workspace',
      },
      {
        id: 'test-env-14',
        name: 'Environmental Drift & Tare Testing',
        code: 'OIML R 76-1 Section 3.5.3.3 & 3.9',
        status: 'PASS',
        summary: 'Tare & thermal certified',
        detail: 'Compliant within statutory limits.',
        observationsCount: 'Corridor verified',
        targetView: 'environmental_workspace',
      },
    ],
    findings: [],
    auditTrail: [
      {
        id: 'audit-14-1',
        time: '15:10',
        iconType: 'complete',
        action: 'Verification testing completed',
        actor: 'P. Joshi (Metrologist)',
      },
      {
        id: 'audit-14-2',
        time: '15:40',
        iconType: 'forward',
        action: 'Peer review completed & approved for Director',
        actor: 'R. Kumar (Technical Reviewer)',
      },
      {
        id: 'audit-14-3',
        time: '16:02',
        iconType: 'sign',
        action: 'Director digitally signed with 4-digit PIN (7620)',
        actor: 'Dr. S. Sharma (Laboratory Director)',
      },
    ],
  },
  {
    id: 'VR-2026-00418',
    sessionNumber: 'VR-2026-00418',
    manufacturer: 'Avery Weigh-Tronix',
    model: 'ZM201 Retail Platform',
    serialNumber: 'AV-2026-8812',
    accuracyClass: 'Class III',
    maxCapacity: '30 kg',
    interval: 'e = 0.005 kg',
    verificationStage: 'Initial Type Approval',
    completedSteps: 4,
    totalSteps: 7,
    status: 'IN_TESTING',
    overallVerdict: 'PASS',
    updatedAt: '2 min ago',
    tests: [
      {
        id: 'test-phys-18',
        name: 'Physical Inspection & Security Audit',
        code: 'OIML R 76-1 Section 3.1 & 4.1',
        status: 'PASS',
        summary: 'All required checks passed',
        detail: 'Hardware verified.',
        observationsCount: '5 / 5 verified',
        targetView: 'physical_inspection',
      },
      {
        id: 'test-weigh-18',
        name: 'Weighing Error & Linearity',
        code: 'OIML R 76-1 Section 3.5.1',
        status: 'PASS',
        summary: 'Complete within tolerance',
        detail: 'Error band compliant.',
        observationsCount: '12 points verified',
        targetView: 'weighing_linearity',
      },
      {
        id: 'test-ecc-18',
        name: 'Eccentricity (Corner Loading)',
        code: 'OIML R 76-1 Section 3.6.2',
        status: 'PASS',
        summary: 'In progress (4 / 5 positions)',
        detail: 'Corner D & E testing underway.',
        observationsCount: '4 positions complete',
        targetView: 'eccentricity_workspace',
      },
    ],
    findings: [],
    auditTrail: [
      {
        id: 'audit-18-1',
        time: '16:15',
        iconType: 'complete',
        action: 'Weighing error run passed',
        actor: 'S. Sharma (Metrologist)',
      },
    ],
  },
];
