import {
  AuditDiscrepancy,
  WeighingRecalcRow,
  EccentricityComparisonRow,
  ExtractedWorkbookMetadata,
} from './types';

export const INITIAL_EXTRACTED_METADATA: ExtractedWorkbookMetadata = {
  fileName: 'Verification_Report_2025.xlsx',
  fileSize: '1.8 MB',
  importedDate: 'Imported just now',
  totalSheets: 3,
  totalRows: 31,
  matchedRows: 27,
  discrepanciesCount: 3,
  highRiskCount: 1,
  manufacturer: 'Avery Weigh-Tronix',
  model: 'ZM201 Retail Platform',
  serialNumber: 'AV-2026-8812',
  accuracyClass: 'Class III',
  maxCapacity: '30 kg',
  minCapacity: '100 g',
  interval: '5 g',
  scaleIntervalsCount: 6000,
  verificationStage: 'Subsequent Verification',
  operator: 'Shashi Shekhar',
  reportDate: '04 Oct 2026',
  laboratory: 'National Legal Metrology Verification Lab',
  workbookSheet: 'Test Report',
  confidentFieldsCount: 24,
  reviewFieldsCount: 2,
  fieldConfidences: [
    {
      field: 'Manufacturer',
      value: 'Avery Weigh-Tronix',
      status: 'CONFIDENT',
      source: 'Nameplate cell B4',
    },
    {
      field: 'Model',
      value: 'ZM201 Retail Platform',
      status: 'CONFIDENT',
      source: 'Nameplate cell B5',
    },
    {
      field: 'Serial Number',
      value: 'AV-2026-8812',
      status: 'CONFIDENT',
      source: 'Found in Nameplate sheet B6',
    },
    {
      field: 'Accuracy Class',
      value: 'Class III',
      status: 'CONFIDENT',
      source: 'Header cell D4',
    },
    {
      field: 'Max Capacity',
      value: '30 kg',
      status: 'CONFIDENT',
      source: 'Test parameters sheet C3',
    },
    {
      field: 'Min Capacity',
      value: '100 g',
      status: 'CONFIDENT',
      source: 'Test parameters sheet C4',
    },
    {
      field: 'Verification Scale Interval (e)',
      value: '5 g',
      status: 'CONFIDENT',
      source: 'Test parameters sheet C5',
    },
    {
      field: 'Verification Stage',
      value: 'Subsequent Verification',
      status: 'REQUIRES_CONFIRMATION',
      source: 'Not explicitly labelled (inferred from interval frequency)',
    },
    {
      field: 'Standard Weight Set Traceability',
      value: 'F1 FW-24-018',
      status: 'REQUIRES_CONFIRMATION',
      source: 'Footer annotation string match',
    },
  ],
};

export const MOCK_DISCREPANCIES: AuditDiscrepancy[] = [
  {
    id: 'F-0017',
    findingNumber: '01',
    sheetName: 'Verification Data',
    rowNumber: 17,
    testName: 'Weighing Error & Linearity',
    loadPoint: '10.000 kg (Tier 2)',
    severity: 'HIGH',
    category: 'FALSE_PASS',
    title: 'False Pass detected (Rounding discrepancy trap)',
    legacyResult: 'PASS',
    recalculatedResult: 'FAIL',
    legacyError: '0.00 g (Observed)',
    correctedError: '-5.3 g (Unrounded Turning Point)',
    difference: '-5.3 g',
    permissibleLimit: '±5.0 g (±1e)',
    summary: 'Legacy rounded value appears compliant after truncation, while digital turning-point recalculation reveals unrounded error exceeding statutory MPE.',
    whyItMatters: 'The legacy spreadsheet naively subtracted integer display values (I - L) and rounded the display to zero, masking a -5.3 g turning-point error that exceeds the statutory legal tolerance of ±5.0 g.',
    statutoryReference: 'OIML R 76-1 Section 3.5.3.2 & Table 6 (Maximum Permissible Errors)',
    calculationSnippet: 'P = I + 0.5e - ΔL = 10.000 + 2.5 - 7.8 = 9.9947 kg ➔ E = -5.3 g > MPE (±5.0 g)',
    legacyFormula: '=ROUND(C17-B17, 2)',
    digitalFormula: 'P = I + 0.5e - ΔL ; E = P - L',
  },
  {
    id: 'F-0022',
    findingNumber: '02',
    sheetName: 'Linearity Analysis',
    rowNumber: 22,
    testName: 'Formula Evaluation Methodology',
    loadPoint: '5.000 kg (1/6 Max)',
    severity: 'MEDIUM',
    category: 'FORMULA_MISMATCH',
    title: 'Formula mismatch (Naive subtraction vs OIML turning point)',
    legacyResult: 'PASS',
    recalculatedResult: 'FAIL',
    legacyError: '+5.0 g',
    correctedError: '+5.2 g',
    difference: '+0.2 g',
    permissibleLimit: '±5.0 g (±1e)',
    summary: 'Legacy formula applied I - L without turning point weights, concealing borderline out-of-tolerance condition.',
    whyItMatters: 'At 5.000 kg, statutory verification requires adding fractional weights to determine turning point to 0.1e accuracy rather than trusting coarse display steps.',
    statutoryReference: 'OIML R 76-1 Section 3.5.3.2 (Determination of Error by Additional Weights)',
    calculationSnippet: 'P = 5.005 + 2.5 - 2.3 = 5.0052 kg ➔ E = +5.2 g (Exceeds ±5.0 g)',
    legacyFormula: '=C22-B22',
    digitalFormula: 'P = I + 0.5e - ΔL',
  },
  {
    id: 'F-0028',
    findingNumber: '03',
    sheetName: 'Header & Metadata',
    rowNumber: 4,
    testName: 'Statutory Verification Metadata',
    loadPoint: 'Sheet 1 Nameplate',
    severity: 'LOW',
    category: 'METADATA_MISMATCH',
    title: 'Missing metadata (Verification stage not explicitly labelled)',
    legacyResult: 'PASS',
    recalculatedResult: 'PASS',
    legacyError: 'Unlabeled',
    correctedError: 'Subsequent Verification (Inferred)',
    difference: 'Metadata Gap',
    permissibleLimit: 'N/A',
    summary: 'Verification Stage was not explicitly labelled in the legacy header, requiring operator confirmation during intake.',
    whyItMatters: 'Statutory certificates must legally state whether the inspection is an Initial Verification or Subsequent Verification to determine MPE multiplier.',
    statutoryReference: 'Legal Metrology (General) Rules, 2011 Schedule VII & OIML R 76-1',
    calculationSnippet: 'Header cell D4 empty ➔ Inferred from previous annual stamp cycle',
    legacyFormula: 'N/A (Raw text)',
    digitalFormula: 'Resolved via Canonical Schema Registry',
  },
];

export const MOCK_WEIGHING_RECALC: WeighingRecalcRow[] = [
  {
    load: '5.000 kg',
    legacyReading: '5.005 kg',
    legacyError: '+5 g',
    digitalError: '+5.2 g',
    legacyResult: 'PASS',
    oimlTurningPoint: '5.0052 kg',
    oimlLimit: '±5.0 g',
    oimlResult: 'FAIL',
    differenceNotes: 'Turning point reveals out-of-tolerance error (+5.2 g > ±5.0 g)',
  },
  {
    load: '10.000 kg',
    legacyReading: '10.005 kg',
    legacyError: '+5 g',
    digitalError: '+5.3 g',
    legacyResult: 'PASS',
    oimlTurningPoint: '10.0053 kg',
    oimlLimit: '±5.0 g',
    oimlResult: 'FAIL',
    differenceNotes: 'FALSE PASS: Unrounded error exceeds MPE tier 1 (+5.3 g > ±5.0 g)',
  },
  {
    load: '15.000 kg',
    legacyReading: '15.000 kg',
    legacyError: '0 g',
    digitalError: '+0.1 g',
    legacyResult: 'PASS',
    oimlTurningPoint: '15.0001 kg',
    oimlLimit: '±10.0 g',
    oimlResult: 'PASS',
    differenceNotes: 'Compliant within Tier 2 (±10.0 g) tolerance band',
  },
  {
    load: '20.000 kg',
    legacyReading: '20.005 kg',
    legacyError: '+5 g',
    digitalError: '+5.1 g',
    legacyResult: 'PASS',
    oimlTurningPoint: '20.0051 kg',
    oimlLimit: '±10.0 g',
    oimlResult: 'PASS',
    differenceNotes: 'Compliant within Tier 2 tolerance',
  },
  {
    load: '25.000 kg',
    legacyReading: '25.010 kg',
    legacyError: '+10 g',
    digitalError: '+10.2 g',
    legacyResult: 'PASS',
    oimlTurningPoint: '25.0102 kg',
    oimlLimit: '±15.0 g',
    oimlResult: 'PASS',
    differenceNotes: 'Compliant within Tier 3 (±15.0 g) tolerance band',
  },
  {
    load: '30.000 kg',
    legacyReading: '30.010 kg',
    legacyError: '+10 g',
    digitalError: '+10.1 g',
    legacyResult: 'PASS',
    oimlTurningPoint: '30.0101 kg',
    oimlLimit: '±15.0 g',
    oimlResult: 'PASS',
    differenceNotes: 'Full scale capacity verified compliant',
  },
];

export const MOCK_ECCENTRICITY_ROWS: EccentricityComparisonRow[] = [
  {
    cornerNumber: 1,
    position: 'A',
    label: 'Top-Left Corner',
    load: '10.000 kg',
    legacyDeviation: '+1.2 g',
    digitalDeviation: '+1.2 g',
    difference: '0.0 g',
    status: 'MATCH',
    legacyResult: 'PASS',
    digitalResult: 'PASS',
    notes: 'Exact match between legacy reading and recalculated deviation',
  },
  {
    cornerNumber: 2,
    position: 'B',
    label: 'Top-Right Corner',
    load: '10.000 kg',
    legacyDeviation: '+0.8 g',
    digitalDeviation: '+0.9 g',
    difference: '+0.1 g',
    status: 'DIFFERENCE',
    legacyResult: 'PASS',
    digitalResult: 'PASS',
    notes: 'Minor rounding offset in legacy cell, within tolerance',
  },
  {
    cornerNumber: 3,
    position: 'C',
    label: 'Bottom-Right Corner',
    load: '10.000 kg',
    legacyDeviation: '+1.5 g',
    digitalDeviation: '+1.4 g',
    difference: '-0.1 g',
    status: 'DIFFERENCE',
    legacyResult: 'PASS',
    digitalResult: 'PASS',
    notes: 'Fractional turning point variance, compliant',
  },
  {
    cornerNumber: 4,
    position: 'D',
    label: 'Bottom-Left Corner',
    load: '10.000 kg',
    legacyDeviation: '-4.1 g',
    digitalDeviation: '-6.2 g',
    difference: '-2.1 g',
    status: 'HIGH-RISK',
    legacyResult: 'PASS',
    digitalResult: 'FAIL',
    notes: 'WORST DIFFERENCE: Legacy sheet failed to account for -2.1 g mechanical deflection, exceeding statutory limit ±5.0 g',
  },
];
