import {
  ReadinessCheckItem,
  PreflightSummary,
  PreflightLifecycleStep,
  NextTestPreview,
  HardwareTelemetry,
} from './types';

export const CANONICAL_PREFLIGHT_STEPS: PreflightLifecycleStep[] = [
  { stepNumber: '01', name: 'Registration & Intake', shortName: 'Registration', status: 'COMPLETED', targetTab: 'intake' },
  { stepNumber: '02', name: 'Physical Preconditions', shortName: 'Preconditions', status: 'COMPLETED', targetTab: 'physical_inspection' },
  { stepNumber: '03', name: 'Test Applicability Plan', shortName: 'Test Plan', status: 'COMPLETED', targetTab: 'test_plan' },
  { stepNumber: '04', name: 'Preflight Readiness Gate', shortName: 'Readiness', status: 'ACTIVE', targetTab: 'readiness' },
  { stepNumber: '05', name: 'OIML Testing Modules', shortName: 'Testing', status: 'UPCOMING', targetTab: 'weighing_linearity' },
  { stepNumber: '06', name: 'Statutory Peer Review', shortName: 'Review', status: 'UPCOMING', targetTab: 'review' },
  { stepNumber: '07', name: 'Certificate Form VI', shortName: 'Certificate', status: 'UPCOMING', targetTab: 'reports' },
];

export const CANONICAL_NEXT_TEST: NextTestPreview = {
  testCode: 'TEST_01',
  name: 'Weighing Error & Linearity',
  standardClause: 'OIML R 76-1 § 3.5.1',
  loadPointsCount: 31,
  mpeLimits: '±0.5 e (0–500 e), ±1.0 e (500–2,000 e), ±1.5 e (>2,000 e)',
  targetView: 'weighing_linearity',
  requiredEvidence: [
    '31 observation load points (ascending & descending)',
    'Zero-setting & tare error calculation',
    'Real-time scale capture or authenticated manual entry',
  ],
};

export const CANONICAL_HARDWARE_TELEMETRY: HardwareTelemetry = {
  port: 'RS-232 COM3',
  baudRate: 9600,
  mode: 'SIMULATOR',
  weightKg: 12.345,
  unit: 'kg',
  isStable: true,
};

export const INITIAL_PREFLIGHT_SUMMARY: PreflightSummary = {
  sessionNumber: 'SES-2026-0046',
  manufacturer: 'Avery Weigh-Tronix',
  model: 'ZM201 Retail Platform',
  serialNumber: 'AV-2026-8812',
  accuracyClass: 'Class III',
  maxCapacity: '30.000 kg',
  minCapacity: '0.100 kg',
  verificationInterval: 'e = 0.005 kg',
  scaleDivisions: 6000,
  verificationStage: 'Subsequent Verification',
  selectedWeightSet: 'F1 • FW-24-018',
  weightSetStatus: 'VALID',
  weightSetDaysRemaining: 182,
  requiredTestCount: 8,
  environmentalBaseline: {
    temperatureC: 23.4,
    temperatureValid: true,
    humidityPercent: 48,
    humidityValid: true,
    pressureHpa: 1008,
    pressureValid: true,
    timestamp: '18:31:42 IST',
    sensorNode: 'BMP-280 Environmental Sensor Node #04 (Calibrated)',
  },
  physicalInspection: {
    spiritLevelPassed: true,
    securitySealPassed: true,
    instrumentConditionPassed: true,
    tamperProofVerified: true,
    remainingChecksCount: 0,
    levelBubbleDeflectionMm: 0.1,
    sealTagNumber: 'IN-DL-2026-0814',
    opticalPhotoCount: 5,
  },
  nextTest: CANONICAL_NEXT_TEST,
  hardwareTelemetry: CANONICAL_HARDWARE_TELEMETRY,
};

// 8 Canonical Statutory Checklist Items (§6, §7, §27)
export const CANONICAL_READY_CHECKLIST: ReadinessCheckItem[] = [
  {
    id: 'CHK-01',
    category: 'REGISTRATION',
    title: 'Instrument registered',
    description: 'Digital intake completed and verification session instantiated in Central LM Lab.',
    status: 'READY',
    severity: 'MANDATORY',
    detail: 'Session SES-2026-0046 created · Operator: Rahul Kumar (Metrologist)',
    statutoryRef: 'Legal Metrology (General) Rules 2011, Rule 27',
    specDetails: {
      'Intake Session': 'SES-2026-0046',
      'Registered At': '04 Oct 2026, 12:45 IST',
      'Laboratory': 'Central LM Laboratory, New Delhi',
      'Stage': 'Subsequent Verification',
    },
    resolutionActionText: 'View Intake Dossier',
    resolutionTargetTab: 'session_detail',
  },
  {
    id: 'CHK-02',
    category: 'IDENTITY',
    title: 'Identification complete',
    description: 'Manufacturer markings, model number, serial number, and TAC confirmed.',
    status: 'READY',
    severity: 'MANDATORY',
    detail: 'Avery ZM201 · AV-2026-8812 · TAC-2026-III-0142 verified',
    statutoryRef: 'OIML R 76-1 Section 8.1 (Marking of Instruments)',
    specDetails: {
      'Manufacturer': 'Avery Weigh-Tronix',
      'Model Identifier': 'ZM201 Retail Platform',
      'Serial Number': 'AV-2026-8812',
      'Approval Certificate': 'TAC-2026-III-0142',
    },
    resolutionActionText: 'View Identification Card',
    resolutionTargetTab: 'session_detail',
  },
  {
    id: 'CHK-03',
    category: 'SPECIFICATIONS',
    title: 'Metrological specifications validated',
    description: 'Max, Min, e, and d parameters passed statutory Table 3 validation rules.',
    status: 'READY',
    severity: 'MANDATORY',
    detail: 'Max 30 kg · Min 100 g · e = 5 g · d = 5 g · n = 6,000 (compliant)',
    statutoryRef: 'OIML R 76-1 Section 3.2 Table 3',
    specDetails: {
      'Accuracy Class': 'Class III (Medium)',
      'Maximum Capacity': '30.000 kg',
      'Minimum Capacity': '0.100 kg (20 e)',
      'Verification Interval (e)': '0.005 kg',
      'Scale Interval (d)': '0.005 kg (d = e)',
      'Divisions (n)': '6,000 (Statutory limit: 500 ≤ n ≤ 10,000)',
    },
    resolutionActionText: 'Open Instrument Details',
    resolutionTargetTab: 'session_detail',
  },
  {
    id: 'CHK-04',
    category: 'SPECIFICATIONS',
    title: 'Accuracy class confirmed',
    description: 'Medium accuracy Class III verified against intended commercial application.',
    status: 'READY',
    severity: 'MANDATORY',
    detail: 'Class III · Verification interval e = 5 g · Complies with Rule 24',
    statutoryRef: 'OIML R 76-1 Section 3.1 & Schedule VI',
    specDetails: {
      'Designated Class': 'Class III (Medium Accuracy)',
      'Application Scope': 'Commercial Retail & Industrial Packaging',
      'Scale Resolution': '1 : 6,000 statutory divisions',
    },
    resolutionActionText: 'View Metrological Specs',
    resolutionTargetTab: 'session_detail',
  },
  {
    id: 'CHK-05',
    category: 'TRACEABILITY',
    title: 'Standard weight traceability valid',
    description: 'Reference standard weight set calibration verified through NPL/RRSL chain.',
    status: 'READY',
    severity: 'MANDATORY',
    detail: 'F1 • FW-24-018 valid through 18 Mar 2027 (182 days remaining)',
    statutoryRef: 'OIML R 111-1 & LM Rules Schedule VII',
    specDetails: {
      'Standard Set': 'F1 • FW-24-018 (Class F1 Stainless Steel)',
      'Calibration Lab': 'NPL / RRSL Regional Standard Laboratory',
      'Certificate ID': 'CERT-NPL-2026-F1-018',
      'Expiry Date': '18 Mar 2027 (Valid)',
    },
    resolutionActionText: 'View Standards Registry',
    resolutionTargetTab: 'standards',
  },
  {
    id: 'CHK-06',
    category: 'TEST_PLAN',
    title: 'Test applicability determined',
    description: '8 statutory test procedures determined for Class III subsequent verification.',
    status: 'READY',
    severity: 'MANDATORY',
    detail: '8 / 8 applicable procedures configured (0 unresolved scope issues)',
    statutoryRef: 'OIML R 76-1 Section A.4 (Examination Procedures)',
    specDetails: {
      'Applicable Procedures': '8 tests scheduled',
      'Test 01 Weighing Error': 'Mandatory (31 test points)',
      'Test 02 Eccentricity': 'Mandatory (10 kg 4-corner test)',
      'Test 03 Repeatability': 'Mandatory (10 cycles @ 24 kg)',
      'Test 04 Environmental Drift': 'Mandatory (+10°C to +40°C)',
    },
    resolutionActionText: 'View Test Plan',
    resolutionTargetTab: 'test_plan',
  },
  {
    id: 'CHK-07',
    category: 'ENVIRONMENT',
    title: 'Required environment recorded',
    description: 'Ambient temperature, relative humidity, and barometric pressure within statutory limits.',
    status: 'READY',
    severity: 'MANDATORY',
    detail: '23.4 °C · 48% RH · 1008 hPa (Auto-populated from lab baseline)',
    statutoryRef: 'OIML R 76-1 Section 3.9.2.1 (Temperature Limits)',
    specDetails: {
      'Temperature': '23.4 °C (Statutory range: +10°C to +40°C)',
      'Relative Humidity': '48% RH (Statutory limit: ≤ 85%)',
      'Atm. Pressure': '1008 hPa (Barometric reference)',
      'Sensor Node': 'BMP-280 Environmental Node #04 (Calibrated)',
    },
    resolutionActionText: 'Inspect Environmental Baseline',
    resolutionTargetTab: 'environmental_workspace',
  },
  {
    id: 'CHK-08',
    category: 'PHYSICAL',
    title: 'Physical precondition confirmed',
    description: 'Spirit level centered, security seal inspected, and load receptor clean.',
    status: 'READY',
    severity: 'MANDATORY',
    detail: 'Level bubble centered (<0.1 mm) · Seal #IN-DL-2026-0814 intact',
    statutoryRef: 'OIML R 76-1 Section 3.9.1 & WELMEC 7.2',
    specDetails: {
      'Spirit Bubble': 'Concentric circle centered (< 0.2 mm deflection)',
      'Security Seal': 'Intact lead-wire seal #IN-DL-2026-0814',
      'Receptor Condition': 'Clean stainless steel pan, free movement',
      'Tamper Evidence': 'Zero casing intrusion detected',
    },
    resolutionActionText: 'Open Physical Inspection Studio',
    resolutionTargetTab: 'physical_inspection',
  },
];

// Attention Checklist (§15 & §18): Standard weight set expiring soon
export const CANONICAL_ATTENTION_CHECKLIST: ReadinessCheckItem[] = [
  ...CANONICAL_READY_CHECKLIST.slice(0, 4),
  {
    id: 'CHK-05',
    category: 'TRACEABILITY',
    title: 'Standard weight traceability valid',
    description: 'Assigned reference standard weight set calibration expires soon.',
    status: 'WARNING',
    severity: 'MANDATORY',
    detail: 'F1 • FW-24-018 expires in 12 days (16 Oct 2026)',
    statutoryRef: 'OIML R 111-1 & LM Rules Schedule VII',
    whyItMatters: 'Calibration certificate will lapse shortly. Testing may proceed under caution, but recalibration is required before next cycle.',
    requiredAction: 'Review standard calibration validity or assign backup weight set E2-015 from registry.',
    resolutionActionText: 'Manage Standard Weights →',
    resolutionTargetTab: 'standards',
  },
  ...CANONICAL_READY_CHECKLIST.slice(5),
];

// Blocked Checklist (§10, §15, §21): Standard weights expired (Hard Lockout)
export const CANONICAL_BLOCKED_CHECKLIST: ReadinessCheckItem[] = [
  ...CANONICAL_READY_CHECKLIST.slice(0, 4),
  {
    id: 'CHK-05',
    category: 'TRACEABILITY',
    title: 'Standard weight traceability valid',
    description: 'Assigned reference standard weight set calibration has expired. Test inputs locked.',
    status: 'BLOCKED',
    severity: 'MANDATORY',
    detail: 'F1 • FW-24-018 EXPIRED on 04 Oct 2026',
    statutoryRef: 'OIML R 111-1 & LM Rules Schedule VII',
    blockerReason: 'Standard weight set FW-24-018 has expired.',
    whyItMatters: 'Testing requires a currently valid traceable reference standard. Statutory verification measurements cannot proceed under legal metrology law.',
    requiredAction: 'Replace expired standard weight set with a currently calibrated set from the registry.',
    resolutionActionText: 'Replace Standard Weights →',
    resolutionTargetTab: 'standards',
  },
  ...CANONICAL_READY_CHECKLIST.slice(5),
];

// Remanded Checklist (§13 & §16): Reviewer requested physical re-inspection
export const CANONICAL_REMANDED_CHECKLIST: ReadinessCheckItem[] = [
  ...CANONICAL_READY_CHECKLIST.slice(0, 7),
  {
    id: 'CHK-08',
    category: 'PHYSICAL',
    title: 'Physical precondition confirmed',
    description: 'Reviewer remanded session: "Repeat physical inspection after seal verification."',
    status: 'WARNING',
    severity: 'MANDATORY',
    detail: 'Remanded by Reviewer: Repeat physical inspection after seal verification',
    statutoryRef: 'OIML R 76-1 Section 3.9.1',
    blockerReason: 'Reviewer note: "Repeat physical inspection after seal verification."',
    whyItMatters: 'A statutory verification cannot proceed to measurement recording while physical precondition audit findings are remanded.',
    requiredAction: 'Open Physical Inspection Studio, verify lead-wire seal placement, and re-certify condition.',
    resolutionActionText: 'Resolve Remand in Inspection →',
    resolutionTargetTab: 'physical_inspection',
  },
];
