import {
  LaboratoryConfig,
  UserRoleItem,
  StandardsConfig,
  TestDefaultsConfig,
  LanguageSettingsConfig,
  CertificateSettingsConfig,
  AppearanceConfig,
  DemoModeConfig,
  SystemStatusInfo,
} from './types';

export const INITIAL_LABORATORY_CONFIG: LaboratoryConfig = {
  id: 'RRSL-BLR',
  name: 'Regional Reference Standards Laboratory',
  code: 'RRSL-BLR',
  city: 'Bengaluru',
  state: 'Karnataka',
  country: 'India',
  labType: 'RRSL',
  nablAccreditationNo: 'NABL-TC-8821',
  nablStatus: 'ACTIVE',
  nablValidUntil: '18/03/2028',
  address: 'Plot No. 12, Peenya Industrial Area, Phase 1, Bengaluru 560058',
  contactEmail: 'director.rrsl-blr@gov.in',
  contactPhone: '+91 80 2839 4500',
  brandingLogoName: 'National_Legal_Metrology_Insignia.svg',
  governmentMarkConfigured: true,
  headerPreviewApproved: true,
};

export const INITIAL_USERS: UserRoleItem[] = [
  {
    id: 'USR-01',
    name: 'Shashi Shekhar (R. Sharma)',
    designation: 'Senior Legal Metrologist',
    email: 'metrologist.shashi@gov.in',
    role: 'METROLOGIST',
    laboratory: 'RRSL Bengaluru',
    status: 'ACTIVE',
    permissions: {
      registerInstruments: true,
      enterObservations: true,
      captureLiveReadings: true,
      submitForReview: true,
      reviewTestDossier: false,
      remandWithJustification: false,
      directorSignOff: false,
      modifySystemSettings: false,
      auditLedgerInspection: true,
    },
  },
  {
    id: 'USR-02',
    name: 'A. Gupta',
    designation: 'Senior Metrological Reviewer',
    email: 'a.gupta@gov.in',
    role: 'REVIEWER',
    laboratory: 'RRSL Bengaluru',
    status: 'ACTIVE',
    permissions: {
      registerInstruments: true,
      enterObservations: false,
      captureLiveReadings: false,
      submitForReview: false,
      reviewTestDossier: true,
      remandWithJustification: true,
      directorSignOff: false,
      modifySystemSettings: false,
      auditLedgerInspection: true,
    },
  },
  {
    id: 'USR-03',
    name: 'A. Kumar (S. Kumar)',
    designation: 'Laboratory Director',
    email: 'director.akumar@gov.in',
    role: 'DIRECTOR',
    laboratory: 'RRSL Bengaluru',
    status: 'ACTIVE',
    permissions: {
      registerInstruments: true,
      enterObservations: false,
      captureLiveReadings: false,
      submitForReview: false,
      reviewTestDossier: true,
      remandWithJustification: true,
      directorSignOff: true,
      modifySystemSettings: false,
      auditLedgerInspection: true,
    },
  },
  {
    id: 'USR-04',
    name: 'P. Das',
    designation: 'Statutory Metrology Auditor',
    email: 'p.das@gov.in',
    role: 'AUDITOR',
    laboratory: 'Central Legal Metrology Wing',
    status: 'ACTIVE',
    permissions: {
      registerInstruments: false,
      enterObservations: false,
      captureLiveReadings: false,
      submitForReview: false,
      reviewTestDossier: false,
      remandWithJustification: false,
      directorSignOff: false,
      modifySystemSettings: false,
      auditLedgerInspection: true,
    },
  },
  {
    id: 'USR-05',
    name: 'R. Singh (Lead Admin)',
    designation: 'Lead IT Metrology Administrator',
    email: 'admin.rsingh@gov.in',
    role: 'ADMIN',
    laboratory: 'National Informatics Metrology Center',
    status: 'ACTIVE',
    permissions: {
      registerInstruments: true,
      enterObservations: true,
      captureLiveReadings: true,
      submitForReview: true,
      reviewTestDossier: true,
      remandWithJustification: true,
      directorSignOff: false,
      modifySystemSettings: true,
      auditLedgerInspection: true,
    },
  },
];

export const INITIAL_STANDARDS_CONFIG: StandardsConfig = {
  defaultWeightSetId: 'FW-24-018',
  requireValidCalibration: true,
  blockTestingWhenExpired: true,
  expiryWarningDays: 30,
  autoSyncWithRegistry: true,
  weightSets: [
    {
      id: 'SET-01',
      setId: 'FW-24-018',
      accuracyClass: 'F1',
      calibrationLab: 'NPL / RRSL Regional Standard Laboratory',
      certificateNumber: 'CERT-NPL-2026-F1-018',
      calibrationDate: '18/03/2026',
      expiryDate: '18/03/2027',
      status: 'VALID',
      daysRemaining: 182,
    },
    {
      id: 'SET-02',
      setId: 'E2-014',
      accuracyClass: 'E2',
      calibrationLab: 'NPL National Physical Laboratory',
      certificateNumber: 'CERT-NPL-2025-E2-014',
      calibrationDate: '15/11/2025',
      expiryDate: '15/11/2026',
      status: 'VALID',
      daysRemaining: 42,
    },
    {
      id: 'SET-03',
      setId: 'M1-2026-08',
      accuracyClass: 'M1',
      calibrationLab: 'State Weights & Measures Testing Unit',
      certificateNumber: 'CERT-SW-2025-M1-08',
      calibrationDate: '10/01/2025',
      expiryDate: '10/01/2026',
      status: 'EXPIRED',
      daysRemaining: 0,
    },
    {
      id: 'SET-04',
      setId: 'F2-2024-99',
      accuracyClass: 'F2',
      calibrationLab: 'Regional Standards Laboratory Kolkata',
      certificateNumber: 'CERT-HP-2024-F2-99',
      calibrationDate: '01/05/2024',
      expiryDate: '01/05/2025',
      status: 'RETIRED',
      daysRemaining: 0,
    },
  ],
};

export const INITIAL_TEST_DEFAULTS: TestDefaultsConfig = {
  defaultVerificationStage: 'Subsequent Verification',
  defaultUnit: 'kg',
  defaultObservationLayout: 'SPLIT_VIEW',
  autoSaveObservations: true,
  autoCaptureStableReadings: true,
  showCalculationProof: 'ON_DEMAND',
  confirmBeforeSubmitting: true,
  enforceZeroTrackingVerification: true,
};

export const INITIAL_LANGUAGE_CONFIG: LanguageSettingsConfig = {
  applicationLanguage: 'ENGLISH',
  certificateLanguage: 'ENGLISH',
  bilingualLayout: 'PARALLEL_COLUMNS',
};

export const INITIAL_CERTIFICATE_CONFIG: CertificateSettingsConfig = {
  defaultFormat: 'PDF_A',
  verificationQrEnabled: true,
  digitalSignatureEnabled: true,
  certificateNumberPrefix: 'CERT',
  nextCertificateId: 'CERT-2026-000185',
  watermarkEnabled: true,
};

export const INITIAL_APPEARANCE_CONFIG: AppearanceConfig = {
  theme: 'LIGHT',
  density: 'COMPACT',
  fontFamily: 'IBM_PLEX_MONO',
  reducedMotion: false,
};

export const INITIAL_DEMO_CONFIG: DemoModeConfig = {
  demoControlsEnabled: true,
  juryDemoAssistantEnabled: true,
  syntheticScenariosEnabled: true,
  virtualScaleSimulatorEnabled: true,
  tamperSimulationEnabled: true,
  availableScenarios: [
    {
      id: 'SCENARIO-1',
      name: 'Passing Baseline Verification',
      description: 'Standard Class III Avery ZM201 retail platform meeting all OIML R 76-1 tolerances.',
      enabled: true,
    },
    {
      id: 'SCENARIO-2',
      name: 'Rounding Discrepancy Trap (False Pass)',
      description: 'Legacy spreadsheet falsely marks PASS while OIML turning-point derivation flags statutory failure.',
      enabled: true,
    },
    {
      id: 'SCENARIO-3',
      name: 'Temperature Drift Thermal Failure',
      description: 'Zero drift of +0.32e/°C exceeds maximum allowable ±0.2e/°C in environmental chamber.',
      enabled: true,
    },
    {
      id: 'SCENARIO-4',
      name: 'Eccentricity Cantilever Deflection',
      description: 'Mechanical deflection at corner 3 exceeds maximum permissible error limits.',
      enabled: true,
    },
    {
      id: 'SCENARIO-5',
      name: 'Class I Micro-Precision Balance',
      description: 'High-precision microbalance with e = 0.001g and Class E2 reference standard weights.',
      enabled: true,
    },
  ],
};

export const INITIAL_SYSTEM_STATUS: SystemStatusInfo = {
  version: 'v1.0.0-demo',
  connectionStatus: 'ONLINE',
  dataSyncStatus: 'SYNCHRONIZED',
  activeNode: 'RRSL-BLR (Regional Reference Standards Laboratory, Bengaluru)',
  lastSavedTimestamp: '04 Oct 2026 • 18:44:12 IST',
  databaseDriver: 'PostgreSQL 16 Enterprise / SQLite Wasm Hybrid',
};
